kits:
  food:
    title: "ss"
    size: 54
    requiredSpace: 10
    commands:
      - ''
      - ''
      - "bc {PLAYER} take kit"
    items:
      0:
        material: DIAMOND
        amount: 43
        name: "sss"
        give: false
      1:
        material: SAND
        amount: 43


kitListInventory:
  title: ""
  size: 54
  container:
    0:
      material: DIAMOND
      kitName: food
      amount: 43
      name: "sss"
      lore:
        - ""
        - "{PLAYER}"
        - "sss"