kits:
  food:
    title: "&9Jedzenie"
    size: 54
    delay: 30
    delayInfo: "30 sekund"
    accessInfo: "Dostępne dla &6VIP"
    noPermission:
      - ""
      - ""
    requiredSpace: 10
    commands:
      - "bc {PLAYER} take kit"
    items:
      0:
        material: DIAMOND
        amount: 43
        name: "sss"
        give: false
      1:
        material: SAND
        amount: 43
respawnKit:
  enable: true
  commands:
    - "bc {PLAYER} respawn kit"
  items:
    0:
      material: DIAMOND
      amount: 12
      name: "sss"

kitListInventory:
  title: ""
  size: 54
  container:
    0:
      material: DIAMOND
      kitName: food
      amount: 43
      name: "sss"
      lore:
        - ""
        - "{PLAYER}"
        - "sss"